apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: user-api
  description: User management API
  tags:
    - go
    - kubernetes
  annotations:
    backstage.io/kubernetes-id: user-api
    backstage.io/kubernetes-namespace: default
spec:
  type: service
  lifecycle: production
  owner: backend-team
  providesApis:
    - user-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: user-api
  description: User management API
spec:
  type: openapi
  lifecycle: production
  owner: backend-team
  definition:
    $text: https://github.com/placeholder-org-33/backend-api-svc/blob/main/openapi.yaml