apiVersion: v1
kind: Service
metadata:
  name: user-api
  namespace: backstage
  labels:
    backstage.io/kubernetes-id: user-api
spec:
  selector:
    app: user-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
